### ISSUE TITLE
Use create_hash in is_valid_hash

### ISSUE THREAD

**Issue by Quy** [GWRon/fluxbb_addon_verysimpleantibot#10]
This calculation is in both functions. 
`md5($text . date('dmYH') . $pun_config['vsab_salt'])`

Perhaps, use `create_hash` in `is_valid_hash`. If yes, `create_hash` will have to be modified to accommodate the previous hour checking.

**Comment by GWRon** [comment]
There is a logical difference between a "create_hash" and a "is_valid_hash" function. The first creates a new hash (outside does not need to know how it is build). The second one validates a given raw text with the potentially corresponding hash (outside does not need to know what is done in there).

The only "improvement" I could do, is to:
- extend `create_hash` to allow time setup (which exposes unneeded details of implementation to outside)
- replace the similar content in `is_valid_hash()` with a corresponding call to `create_hash()`

Currently both functions do not do that much of complicated (php-code wise) things that needs to exchange that code portion with the function call.
The current implementation has the benefit of directly revealing the difference between the two hash-validations.

If you intend to extend the "answer-is-valid-time" and to make it even more flexible (-30 minutes, ...) then you could of course extend the both functions to make it work ... But even this would be easily done with an added param to the `ìs_valid_hash()` function. I will leave it up to you :smiley: .

**Comment by Quy** [comment]
`replace the similar content in is_valid_hash() with a corresponding call to create_hash()`.
I had this in mind, but I see your points.
