### ISSUE TITLE
Use array_rand

### ISSUE THREAD

**Issue by Quy** [GWRon/fluxbb_addon_verysimpleantibot#11]
This could be simplified:

```
//load in the questions of the question=>answer array
$questions = array_keys($addon_vsab_questions);
//choose random question index and generate hash
$this->chosen_question = $questions[ rand(0, count($questions)-1) ];
```

to:
`$this->chosen_question = array_rand($addon_vsab_questions);`

**Comment by GWRon** [comment]
I thought about this too, I am not sure but array_rand seems to return an array in some cases:

``` PHP
<?php
$input = array("Neo", "Morpheus", "Trinity", "Cypher", "Tank");
$rand_keys = array_rand($input, 2);
echo $input[$rand_keys[0]] . "\n";
echo $input[$rand_keys[1]] . "\n";
?>
```

http://php.net/manual/function.array-rand.php

Don't know how "stable" that command is ... if it changes to "always array" we run into problems ... but ok.

An even more problematic part: array_rand returns a random key not a associative pair or the value.

So we could only change it to:

``` PHP
$this->chosen_question = $addon_vsab_questions[ array_rand($addon_vsab_questions) ];
```

Which might do the job, but I am not sure whether it is worth the hassle?

**Comment by GWRon** [comment]
Edit: Ok ... I  was dumb ... as we store the question in the key, there is no problem to use `array_rand`... 

You are right, commit coming soon
