### ISSUE TITLE
Add a comma to the last question/answer entry

### ISSUE THREAD

**Issue by Quy** [GWRon/fluxbb_addon_verysimpleantibot#2]
`'Fill in the missing letters: Are you a human or a c**puter??'    => "om"`
Just in case this entry is copied and the admin forgets to add a comma before pasting it after this entry.

**Comment by GWRon** [comment]
Sharp Eyes ... will fix in 1 minute (I am used to not have "," for the latest array entry because not all languages allow that ... so apologize this).
