### ISSUE TITLE
No captcha value in required_fields

### ISSUE THREAD

**Issue by Quy** [GWRon/fluxbb_addon_verysimpleantibot#3]
```
    var required_fields = {
        "req_user": "Username",
        "req_password1": "Password",
        "req_password2": "Confirm password",
        "req_email1": "Email",
        "req_email2": "Email 2",
        "captcha": ""
    };
```

**Comment by GWRon** [comment]
Gets fixed with next commit.

Next time I should check my popup-blocker as it blocks "alerts" in most cases.

**Comment by Quy** [comment]
It is still empty.

**Comment by Quy** [comment]
It is still empty so you don't get the JavaScript alert box.
`"vsab_answer": ""`

**Comment by GWRon** [comment]
is `$lang_addon_vsab['title'];` set correctly? For me it outputs correctly the text configured in the lang files.

Edit: ok it is empty now ... will check why (I just had a test before committing and it worked ... must have missed to transport something to my local git repo -> I test it on a local installation without symlinks to the addon files so it is copy paste and I seem to have had mixed up something)

**Comment by Quy** [comment]
...and load in posting too.

**Comment by GWRon** [comment]
Seems I should take a break from the computer ... in my mind I thought it was the "only for registration" part (the username function).

Thanks for your hawk eyes.
