### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by Quy** [GWRon/fluxbb_addon_verysimpleantibot#5]
line 239: `$questions = array();`
Remove since unused in the function.

line 276: `<?php if (isset($action) && $action == 'registration') : ?>`
`$action` defaults to empty string in the argument so not necessary to check with `isset`.

**Comment by GWRon** [comment]
Did not know that function params are always "set", even with explicit "null" passed when calling the function. Have read about it this morning and you are right: get rid of the check.

Commit coming in some minutes.
