### ISSUE TITLE
Register only applicable hooks?

### ISSUE THREAD

**Issue by Quy** [GWRon/fluxbb_addon_verysimpleantibot#6]
I am not sure if this is better to do `have_to_check_user` in register function and only register the applicable hooks. Then you don't need to do this check within the other functions.

**Comment by GWRon** [comment]
I do not know how the things will change in the future. For now "register" is called everytime a page gets rendered (aka the "addons.php" is required from another file).

If I now move that user check into the register function, I must ensure that both used globals are existent already. I do not know when they get populated, that is why the check is done when the hook is called.

But for now I get your point and it is absolutely valid regarding unneeded function calls.

Ideas how to handle the situation described above?

**Edit:** for $pun_config I know that I assume the existence already, dunno what's up with the $pun_user?

**Comment by GWRon** [comment]
This would be the new register function according to your suggestion:

``` php

    //register to all hooks the addon is interested in
    //function is auto-called by the addon-system during boostrapping
    function register($manager)
    {
        if ($this->is_configured())
        {
            global $pun_config;
            //addon disabled -> do not register for any hooks
            if ($pun_config['vsab_enabled']=='no') return false;

            //hook into the registration process
            $manager->bind('register_before_header', array($this, 'hook_register_before_header'));
            $manager->bind('register_before_submit', array($this, 'hook_register_before_submit'));
            $manager->bind('register_before_validation', array($this, 'hook_register_before_validation'));


            //secure (quick-) posting with captcha too?
            if ($pun_config['vsab_enabled_postings'] != 'no')
            {
                global $pun_user;
                //only secure against non-members
                if ($pun_user['is_guest'])
                {
                    //hook into the posting process
                    $manager->bind('post_before_header', array($this, 'hook_post_before_header'));
                    $manager->bind('post_before_submit', array($this, 'hook_post_before_submit'));
                    $manager->bind('post_before_validation', array($this, 'hook_post_before_validation'));

                    //hook into the (quick-) posting process
                    //for now we just reuse the same code of the posting_process
                    //but without "header", as we do not modify the required_fields
                    $manager->bind('quickpost_before_submit', array($this, 'hook_post_before_submit'));
                    $manager->bind('quickpost_before_validation', array($this, 'hook_post_before_validation'));
                }
            }
        }
    }
```

Did I miss something?

**Comment by Quy** [comment]
Looks good!

**Comment by GWRon** [comment]
Do you know by any chance wether "$pun_user['is_guest']" might change inbetween script execution? Eg . in hook 1 the user is listed as member, in a hook 2 the core invalidates that information and therefore the user is now a guest. Now in hook 3 we hook in and assume that the information of hook 1 is still valid.

Do you get what I mean?

old approach: revalidating information on each function (hook) call
new approach: checking once, trusting that information the rest of the execution time.

**Comment by Quy** [comment]
You bought up a good point. 

To test it, I added `print_r($pun_user);` and it displayed Guests values so we should be good.

```
                global $pun_user;
                //only secure against non-members
        print_r($pun_user);
                if ($pun_user['is_guest'])
```

**Comment by GWRon** [comment]
Yes in the current situation this value is there. But I am not sure whether 'is_guest' might change inbetween.

Imagine there are 20 hooks with various listeners, we hook into hook 1of20, check for 'is_guest' there ... everything fine. Next comes hook 2of20, we do not listen to it, but something is invalidating the user there ... maybe some faulty post content or so. Ok, so now to hook 3of20, we listen to it again and when running our code we still assume that the old 'is_guest' state of hook 1of20 is still valid.

Normally such things could be handled by introducing more and more hooks: "change_user_state"-hooks etc - which we would have to listen too (of course we would need to listen to "after_change_user_state").

This problem is overcome by not using "cached outside information" thus we call the user check each time.

Ideas?

**Comment by Quy** [comment]
I understand your concerns now. Unfortunately, I don't know.

On a side note, this should be checked for Guests only too.

```
            //hook into the registration process
            $manager->bind('register_before_header', array($this, 'hook_register_before_header'));
            $manager->bind('register_before_submit', array($this, 'hook_register_before_submit'));
            $manager->bind('register_before_validation', array($this, 'hook_register_before_validation'));
```

**Comment by GWRon** [comment]
good catch. I cleaned up that code too, I thought of having various options in the AP panel (like "captcha for members too") which would benefit from an extra-user-check function to keep things clean - without that advanced option it is a bit useless to provide two options at all (registering - posting). So eg. a posting count of a member could decide whether to use captcha or not.

The current version would look like this:

``` php
//register to all hooks the addon is interested in
    //function is auto-called by the addon-system during boostrapping
    function register($manager)
    {
        if ($this->is_configured())
        {
            global $pun_config;
            //addon disabled -> do not register for any hooks
            if ($pun_config['vsab_enabled']=='no') return false;

            //for now we only validate guests, there is no special
            //"validate member postings" mode yet
            global $pun_user;
            if ($pun_user['is_guest'])
            {
                //hook into the registration process
                $manager->bind('register_before_header', array($this, 'hook_register_before_header'));
                $manager->bind('register_before_submit', array($this, 'hook_register_before_submit'));
                $manager->bind('register_before_validation', array($this, 'hook_register_before_validation'));

                //secure (quick-) posting with captcha too?
                if ($pun_config['vsab_enabled_postings'] != 'no')
                {
                    //hook into the posting process
                    $manager->bind('post_before_header', array($this, 'hook_post_before_header'));
                    $manager->bind('post_before_submit', array($this, 'hook_post_before_submit'));
                    $manager->bind('post_before_validation', array($this, 'hook_post_before_validation'));

                    //hook into the (quick-) posting process
                    //for now we just reuse the same code of the posting_process
                    //but without "header", as we do not modify the required_fields
                    $manager->bind('quickpost_before_submit', array($this, 'hook_post_before_submit'));
                    $manager->bind('quickpost_before_validation', array($this, 'hook_post_before_validation'));
                }
            }
        }
    }
```

The old approach (just use the check function in the register function instead everywhere) would be:

``` php
    //register to all hooks the addon is interested in
    //function is auto-called by the addon-system during boostrapping
    function register($manager)
    {
        if ($this->is_configured())
        {

            if ($this->have_to_check_user("registration"))
            {
                //hook into the registration process
                $manager->bind('register_before_header', array($this, 'hook_register_before_header'));
                $manager->bind('register_before_submit', array($this, 'hook_register_before_submit'));
                $manager->bind('register_before_validation', array($this, 'hook_register_before_validation'));
            }

            if ($this->have_to_check_user("posting"))
            {
                //hook into the posting process
                $manager->bind('post_before_header', array($this, 'hook_post_before_header'));
                $manager->bind('post_before_submit', array($this, 'hook_post_before_submit'));
                $manager->bind('post_before_validation', array($this, 'hook_post_before_validation'));

                //hook into the (quick-) posting process
                //for now we just reuse the same code of the posting_process
                //but without "header", as we do not modify the required_fields
                $manager->bind('quickpost_before_submit', array($this, 'hook_post_before_submit'));
                $manager->bind('quickpost_before_validation', array($this, 'hook_post_before_validation'));
            }
        }
    }
```

Looks nice enough and is a bit more extendable then to do everything directly in the function. But of course it adds more function calls and does things multiple times (checking if enabled at all etc. - but the register function then does not need to know the specific implementation in the user-check-function)

**Comment by Quy** [comment]
Perfect!!

PS: I see one downside with this addon in that once the spammer knows the hash value and the answer, then it can be remotely submitted over and over to bypass the captcha. I don't know if this is something you want to address.

**Comment by GWRon** [comment]
I thought of that too. I thought about adding the date as a salt. The date would change once a day. So this means, if you open the page at 23:59 of the day and submit it 00:02 you get the captcha wrong. But just refill it and it will be valid the next time.

Using a predefined hash (even using the configuration page of the AP panel) could get saved once and for all - nothing we want to have.

Edit: so the best is to have the day hashed into it **plus** a userconfigured hash. Hmm but this might be needless because people will not that easily split apart "date" from original question hash.

Other suggestions?

**Comment by Quy** [comment]
`Looks nice enough and is a bit more extendable then to do everything directly in the function.`
I had this in mind in my initial posting. :)

There is a one hour IP flood registration protection. How about doing a date+hour hash so the same hash/answer cannot be used the same day?

**Comment by GWRon** [comment]
I am already testing it ... currently it is a "dmy" hash. The more narrow we set the timeframe, the more often an valid answer gets invalidated.

We could use the 12h/day-code, so the captcha hash is only valid for 12 hours. Another way would be to store a "dmy"+floor(hour/4) so it is valid for 4 hours - but every 4th hour is then having the above described problem.

In all other cases the captcha should provide the information of "creation date" - which needs to be symmetrical encrypted - which means somehow the used encryption key could get reverseassembled.

**Comment by Quy** [comment]
I am okay with any timeframe. Anything is better than the current system so it can't be shared and be used indefinitely until question/answer(s) are changed.

**Comment by GWRon** [comment]
checkout the new commit d99e8b476 and give feedback of what you think about that.

**Comment by Quy** [comment]
At a quick glance, it looks really good! I have to step out for the moment and will give it a test run in an hour.

**Comment by GWRon** [comment]
Will remove the unused $pun_user in the hash generation. So no need to report that :p

**Comment by Quy** [comment]
Should admins/moderators be excluded for `yes_for_all`?

**Comment by GWRon** [comment]
Maybe I should add a third option then - or better just do not check mods/admins at all - because spammers wont get promoted to mods/admins - and once they got admin, they could disable the addon.

**Comment by Quy** [comment]
Rethinking this, wouldn't it be a nuisance for members to keep having to verify with each posting if enabled? I can see for up to a number of postings, but beyond that disable it as you suggested earlier.

**Comment by GWRon** [comment]
I will add a "min post count" thingy to the configuration which (if > 0) will disable user post validation if they reached that count.

**Comment by GWRon** [comment]
Ok ... I added another option - this allows to set a minimum post count which the member has to have to get rid of the captcha/validation as soon as the "Yes for all" is activated.

**Comment by Quy** [comment]
I think we are good!
PS: Thanks for listening/implementing these changes!

**Comment by GWRon** [comment]
I have to thank for your kind co-work. I will close the issue now, feel free to open another one.
